services:
  postgres:
    image: postgres:15-alpine
    container_name: insider-threat-db
    environment:
      POSTGRES_DB: insider_threat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insider-threat-network

  backend:
    build:
      context: ./backend-fastapi
      dockerfile: Dockerfile
    container_name: insider-threat-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@postgres:5432/insider_threat
      ENVIRONMENT: production
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/app/videos
    depends_on:
      - postgres
    networks:
      - insider-threat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: insider-threat-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/graphql
      NEXT_PUBLIC_VIDEO_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - insider-threat-network

volumes:
  postgres_data:

networks:
  insider-threat-network:
    driver: bridge
